### ISSUE TITLE
Does it work with Google Sheets????

### ISSUE THREAD

**Issue by fxkopp** [michaelneu/webxcel#19]
Otherwise it's useless for me!

**Comment by fxkopp** [comment]
@michaelneu requesting immediate answer

**Comment by michaelneu** [comment]
Thanks for your question. Unfortunately, Google Sheets doesn't support VBA, yet. I'll happily accept a PR adding support for that if you want to work on it!

**Comment by marc101101** [comment]
@michaelneu "yet" :D
